name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'

jobs:
  build:
    uses: mistre83/shared-workflows/.github/workflows/build.yml@main
    secrets: inherit
