name: PR Checks

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'
      - '.release-please-manifest.json'

jobs:
  pr-checks:
    uses: mistre83/shared-workflows/.github/workflows/pr-checks.yml@main
    secrets: inherit

  size-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: 10
          s_max_size: 50
          m_max_size: 200
          l_max_size: 500
          fail_if_xl: false
