name: Release Please

on:
  push:
    branches: [main]
    paths:
      - 'CHANGELOG.md'
      - 'version.txt'

jobs:
  release-please:
    uses: mistre83/shared-workflows/.github/workflows/release-please.yml@main
    secrets: inherit
